name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t vowel-frequency-analyzer:latest .
    
    - name: Run Docker Ccontainer
      run: |
        docker run --rm \
          -e GITHUB_USER="${{ github.actor }}" \
          vowel-frequency-analyzer:latest
